language: node_js
branches: 
  only: 
  - master
env: 
  global: 
    secure: aPDwBjAUky3wVkMP0UMxbjVmtZZER9p2Jt40zXw2xvjmCJC3lEI4vpF1PG5RcJIy+SUrc3pem4N3OxtEnFwOad/E2SW9AcY9JDc7wGrncOaNWJ60SBGn9NPwVLFNpxsYBLvMTlnqbMvLSqceyOP1t3H6bI8oEmenT7RL7Yli2Ss=
script: ./node_modules/.bin/grunt publish
node_js: 
- "0.10"
