language: node_js
branches: 
  only: 
  - master
env: 
  global: 
   secure: "cq+PC0CRoJjoL693bBFO1tllw/yC7sgwb1CnuzWHakuyGRFrpbmQravk5I3ns5oXJTSP0wfl1B3uwf3q4PGiXglHJUGMsxbCC2oGlfFwwjSq52Jrs2pAfBeee02VJV3OT08Ae380jjp1eL3OckBPAGdC5tVfQ6JxYDfmBB5oFRk="
script: ./node_modules/.bin/grunt publish
node_js: 
- "0.10"
